### ISSUE TITLE
Savile Row: Missing toFlatzinc method.

### ISSUE THREAD

**Issue by JasperNL** [conjure-cp/conjure#435]
This happens with the latest binaries on ubuntu 18.04 LTS through the linux subsystem for windows.

```
jasper@S132664:/mnt/d/Desktop/School/ACP summer school/Essence Lab/group work$ conjure solve problem034.essence data_large.param --solver=chuffed
Using cached models.
Savile Row: model000001.eprime data_large.param
Running minion for domain filtering.
Error:
    Savile Row stdout: Created output file for domain filtering conjure-output/model000001-data_large.eprime-minion
Missing toFlatzinc method. type:savilerow.expression.ElementOne

    Savile Row stderr: Exception in thread "Thread-0" java.lang.AssertionError
        at savilerow.expression.ASTNode.toFlatzinc(ASTNode.java:597)
        at savilerow.expression.And.toFlatzinc(And.java:251)
        at savilerow.expression.Top.toFlatzinc(Top.java:41)
        at savilerow.model.Model.toFlatzinc(Model.java:493)
        at savilerow.model.ModelContainer.fznFlattening(ModelContainer.java:1391)
        at savilerow.model.ModelContainer.postFlattening(ModelContainer.java:931)
        at savilerow.model.ModelContainer.process(ModelContainer.java:64)
        at savilerow.SRWorkThread.run(SRWorkThread.java:87)

    Savile Row exit-code: 0
```

**Comment by ozgurakgun** [comment]
Just to give a way of reproducing this.

In the EssenceCatalog repo, run 

```
~/repos/github/EssenceCatalog/problems/csplib-prob034> conjure solve WarehouseLocation.essence params/easy.param --solver=minion
Using cached models.
Savile Row: model000001.eprime params/easy.param
Running minion for domain filtering.
Running solver: minion
Copying solution to: WarehouseLocation-easy.solution


~/repos/github/EssenceCatalog/problems/csplib-prob034> conjure solve WarehouseLocation.essence params/easy.param --solver=glucose
Using cached models.
Savile Row: model000001.eprime params/easy.param
Running minion for domain filtering.
Running solver: glucose
Copying solution to: WarehouseLocation-easy.solution

~/repos/github/EssenceCatalog/problems/csplib-prob034> conjure solve WarehouseLocation.essence params/easy.param --solver=gecode
Using cached models.
Savile Row: model000001.eprime params/easy.param
Running minion for domain filtering.
Error:
    Savile Row stdout: Created output file for domain filtering conjure-output/model000001-easy.eprime-minion
Missing toFlatzinc method. type:savilerow.expression.ElementOne

    Savile Row stderr: Exception in thread "Thread-0" java.lang.AssertionError
	at savilerow.expression.ASTNode.toFlatzinc(ASTNode.java:597)
	at savilerow.expression.And.toFlatzinc(And.java:251)
	at savilerow.expression.Top.toFlatzinc(Top.java:41)
	at savilerow.model.Model.toFlatzinc(Model.java:493)
	at savilerow.model.ModelContainer.fznFlattening(ModelContainer.java:1391)
	at savilerow.model.ModelContainer.postFlattening(ModelContainer.java:931)
	at savilerow.model.ModelContainer.process(ModelContainer.java:64)
	at savilerow.SRWorkThread.run(SRWorkThread.java:87)

    Savile Row exit-code: 0
```

So minion and glucose finds a solution, gecode/chuffed won't.

**Comment by pwn1** [comment]
Fixed.

**Comment by ozgurakgun** [comment]
Thanks @pwn1!

I should change the SR I bundle with Conjure as well. I'll reopen the issue to track progress on that.

**Comment by pwn1** [comment]
That's easy, chuck the jar file into your repository...
